### ISSUE TITLE
v10采集v8不支持繁体？

### ISSUE THREAD

**Issue by skin007** [magicblack/maccms8#1]
令人黯然神傷的愛情故事杭州富家青年樊家樹（宗華）雖被賣藝女子秀姑（施思）及財政廳長之女麗娜（李菁）所愛，但他卻鍾情於歌女沈鳳喜（井莉）。樊回杭州徵得母親同意婚事之際，鳳喜竟被她的舅父三弦出賣，被騙到少帥（馮淬帆）府中，終被少帥迷姦，被迫成為他的姨太太。樊回來知悉，大為悲痛，誓救鳳喜出魔掌。在關秀風（陳觀泰）、秀姑、麗娜的幫助下，終於將少帥殺掉，並將鳳喜救出，眾人逃至碼頭，但追兵窮追不捨，結果不幸的事發生了……

**Comment by magicblack** [comment]
都是utf8点版本，支持繁体中文。

**Comment by skin007** [comment]
那就怪了
我查询了提示xml 错误的页面所有视频 简介  字段也没出现非法字符
