### ISSUE TITLE
数据库升级脚本好像无法升级

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms8#10]
你好，程序我已经更新到1006，然后登录后台，发现有数据库更新提示

提示，发现本地有数据库升级脚本？是否执行升级操作！执行完毕后将自动删除脚本！

之后，我进行了升级操作，也提示 

更新数据缓存文件……
升级完毕……

但是，系统还是提示
提示，发现本地有数据库升级脚本？是否执行升级操作！执行完毕后将自动删除脚本！

请问是不是因为我使用阿里rds的原因？
因为我本地搭建的测试环境应用和数据库在一个服务，升级数据库没有问题。

**Comment by magicblack** [comment]
因为升级完毕后需要删除 后台目录下的 bak/database.php 文件， 是不是没有权限。

**Comment by aoerboquartz** [comment]
确实如老大所说。
确实是那个文件夹权限问题。
