### ISSUE TITLE
你好，升级后，定时任务无法运行了

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms8#11]
提示的内容是
您的提交带有不合法参数,谢谢合作!,操作IP:  ,操作时间: 2020-01-01 20:50:26,操作页面:/inc/timming.php,提交方式: GET

**Comment by magicblack** [comment]
升级到1010试试看。

**Comment by aoerboquartz** [comment]
你好，我从1006，升级到1010 之后。
打开网站就提示
您的提交带有不合法参数,谢谢合作!,操作IP: 192.168.31.211,操作时间: 2020-01-02 09:03:53,操作页面:/index.php,提交方式: GET

我这是本地测试环境。所以IP是 192.168.31.211

**Comment by aoerboquartz** [comment]
后台可以正常访问。
但是 测试定时任务的时候，还是 提示
您的提交带有不合法参数,谢谢合作!,操作IP: 192.168.31.211,操作时间: 2020-01-02 09:08:46,操作页面:/inc/timming.php,提交方式: GET

**Comment by aoerboquartz** [comment]
我好像是从1002 直接升级包 升级到1006，然后升级包升级到 1010的。

**Comment by magicblack** [comment]
修复了1012

**Comment by aoerboquartz** [comment]
你好，问题依旧啊，已经升级到1012了。

您的提交带有不合法参数,谢谢合作!,操作IP: 192.168.31.211,操作时间: 2020-01-02 17:05:50,操作页面:/index.php,提交方式: GET

您的提交带有不合法参数,谢谢合作!,操作IP: 192.168.31.211,操作时间: 2020-01-02 17:06:01,操作页面:/inc/timming.php,提交方式: GET
