### ISSUE TITLE
升级到1007后自定义采集参数有错误

### ISSUE THREAD

**Issue by vod3166** [magicblack/maccms8#13]
升级到1007后自定义采集参数有错误。
酷云资源,?m=collect-list-xt-1-ct--group--flag-kuyunzy-apiurl-http://www.kuyun9.com/inc/ldg_kkm3u8.asp
添加上面的采集源无法显示。别的采集源正常就这个不正常感觉是这个位置的问题，/ldg_kkm3u8.asp
添加后quickmenu.txt文件里变成ldg\_kkm3u8.asp这样，不知道现在好了没。

**Comment by vod3166** [comment]
quickmenu.txt文件里变成ldg  \  _ kkm3u8.asp这样

**Comment by magicblack** [comment]
更新到最新的即可解决

**Comment by magicblack** [comment]
更新到最新的即可解决
