### ISSUE TITLE
这次升级后出现性能问题，CPU100%满，【严重】

### ISSUE THREAD

**Issue by ifpeak** [magicblack/maccms8#15]
同样的流量访问，我回退上一次版本，cpu立刻下降，升级版本cpu撑不住，502，非常严重，请求修复

**Comment by ifpeak** [comment]
我刚刚测试一下，是template文件出现的问题，请老王修复一下吧！

**Comment by magicblack** [comment]
这次主要是为了防止挂马。。。做了简单的调整，升级到1013试试是否有一些好转。
