### ISSUE TITLE
v8拼音不识别数字和字母

### ISSUE THREAD

**Issue by M-pub** [magicblack/maccms8#17]
v8拼音不识别数字和字母，url设置成拼音得时候，采集资源，只会自动生成汉字拼音，不会识别数字和字母，最早以前是可以的！v10测试可以正确识别！
比如：庆余年2019
生成qingyunian.html
希望能自动识别生成qingyuanian2019.html

**Comment by magicblack** [comment]
确认修复稍后更新

**Comment by M-pub** [comment]
> 确认修复稍后更新

请问昨晚22点更新了蓝奏云,是否修复了拼音?
