### ISSUE TITLE
BUG 2019.1016版本采集api 采选中多个会出现-没有任何可用数据

### ISSUE THREAD

**Issue by diaosi123** [magicblack/maccms8#24]
2019.1016版本采集api接口BUG
选多个内容  采集选中-出现 没有任何可用数据
单独采集一个，没有问题
例如：
http://ww.xxx.com/inc/api.php?ac=videolist&rid=&ids=111,222,333

就显示空白内容

**Comment by magicblack** [comment]
修复了更新到1017即可。
