### ISSUE TITLE
生成多个栏目列表的时候错误

### ISSUE THREAD

**Issue by zhengnan06577** [magicblack/maccms8#25]
第0页kongbupian/index-0.html
第1页kongbupian/index.html

从第0页开始，打开显示vod标签出错!

**Comment by magicblack** [comment]
多选栏目 点击生成？

**Comment by M-pub** [comment]
> 多选栏目 点击生成？

当天栏目，或者全部栏目，都是从0开始生成

**Comment by magicblack** [comment]
修复了~~~
