### ISSUE TITLE
还是我，刚刚不小心又发现了一处安全漏洞（重要）

### ISSUE THREAD

**Issue by aTenb** [magicblack/maccms8#28]
感谢老大及时回复我上一条ISSUES!
刚刚发现一处安全漏洞。
后台根目录  index.php 第28行
    if($method!='login' && $method!='check'){
    	chkLogin();
    }
这个逻辑check就不会验证登录信息了。
那么后台所有文件应该避免method为这2个值。但是后台检测数据库木马得文件逻辑是?m=db-check
已经验证，只要知道后台路径，即可在无登录得情况下执行以下程序。
http://www.xxxx.com/admin/index.php?m=db-check
可见，这个文件无需登录就可以操作mysql。
所以，只要存在一个漏洞或者报错暴露了后台路径，黑客就有机会攻击数据库。
可以推断这次挂马有可能就是依靠这个漏洞注入得mysql，虽然暴露后台路径得漏洞还不得而知。
忘修复。

一直坚持用8X，简单易用，忘老大继续维护8X。

**Comment by magicblack** [comment]
嗯，感谢提交，后续将修改这个文件函数
