### ISSUE TITLE
搜索页建议

### ISSUE THREAD

**Issue by M-pub** [magicblack/maccms8#29]
/index.php?m=vod-search
空内容搜索页可以F5无限刷新，后台设置的搜索间隔无效。
例如打开 www.xxxx.com/index.php?m=vod-search 然后F5无限刷新，因为是动态页，会占服务器资源，一直刷新就cc了

**Comment by aTenb** [comment]
有效啊

**Comment by M-pub** [comment]
> 有效啊

多试几遍，会失效的

**Comment by magicblack** [comment]
没问题啊。会提示等待几秒后访问

**Comment by youloulea** [comment]
字段过滤之后搜索有点问题了。例如搜索外国人的影片：蕾切尔·布罗斯纳安，这个名字中间有一个字符，但是搜索时会被过滤掉，导致搜索不出来影片了。

**Comment by M-pub** [comment]
> 没问题啊。会提示等待几秒后访问

搜索框什么都别输入，然后点搜索，出来页面了，复制当前页链接，这时候粘贴打开，就可以f5了
