### ISSUE TITLE
老大，麻烦你看看，我昨天编辑掉了，我觉得还是应该给你说下这个优化的地方

### ISSUE THREAD

**Issue by aTenb** [magicblack/maccms8#33]
二开接口replaceTplCustom()位置能否前移至this->base()前，优先解析用户自定义标签和函数。昨天写了一大推理由，看老大一直没回复，后面找到了新方法就编辑掉了，虽然新方法可以绕开一些，但是更复杂了，所以还是希望老大能采纳迁移或者在base()前也加一个二开接口。昨天内容不知道老大看到没有，大致意思就是移至base()前，二次开发可以把用户标签和官方标签相结合，节省很大的开发量。可以实现类似{maccms:vod xxx={custom:diyxxx} by=time}xxxxx{/maccms:vod}等复杂的自定义功能。

**Comment by zubeeee** [comment]
理由昨天编辑掉了，老大可以看看邮件记录，或者告诉我一下，我重新打一遍优化后的好处。
我先说说我昨天是怎么认为可以解决这个问得吧。{maccms:vod xxx={custom:diyxxx} by=time}xxxxx{/maccms:vod} 我把他整体变成{custom:vod xxx={custom:diyxxx} by=time}xxxxx{/custom:vod} 这样就可以在不变位置的情况下先解析{custom:diyxxx} 再通过$tpl->datalist()解析{custom:vod｝。所以我就编辑掉了昨天的内容。但是我今天发现了也不完美，更复杂了不说，有些地方不起作用。所以最完美得还是replaceTplCustom()迁移至this->base()前，或者在this->base()前再加一个自定义接口。

**Comment by zubeeee** [comment]
又研究了下 好像可以通过继承$AppTpl类重写里面的mark()函数，然后就可以再base()前加一个新接口了。目前测试有效，希望没有弊端

**Comment by zubeeee** [comment]
又研究了下 好像可以通过继承$AppTpl类重写里面的mark()函数，然后就可以再base()前加一个新接口了。目前测试有效，希望没有弊端
