### ISSUE TITLE
马克思cms转换苹果报错，31行，说没有变量

### ISSUE THREAD

**Issue by 77372109** [magicblack/maccms8#36]
马克思cms转换苹果报错，31行，说没有变量，请用土豆详谈，加了有一段时间了。一直发不出去消息

**Comment by magicblack** [comment]
你的隐私设置有问题，所以无法发送消息吧

**Comment by 77372109** [comment]
这个工具 不是最新版，最新版已经修复了马克思的错误，麻烦修改一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"magicblack"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月19日(星期天) 下午2:17
收件人:&nbsp;"magicblack/maccms8"<maccms8@noreply.github.com&gt;;
抄送:&nbsp;"千米"<77372109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms8] 马克思cms转换苹果报错，31行，说没有变量 (#36)




你的隐私设置有问题，所以无法发送消息吧

**Comment by magicblack** [comment]
1、首先在windows的“服务”里面检查COM+服务是否已经启动。如果未启动，请启动它。

2、检查php目录ext文件夹下面php_com_dotnet.dll是否存在。（顺便说一下，ext通常作为php程序的扩展目录，在安装php的时候一般已经设置好。否则就应该不仅仅报主题所说的错咯。）

3、如果没问题，在php.ini里面加入以下语句：

[PHP_COM_DOTNET]
extension=php_com_dotnet.dll
4、php.ini中设置

com.allow_dcom = true
