### ISSUE TITLE
新版本视频介绍标签一片一片空白

### ISSUE THREAD

**Issue by Svipa** [magicblack/maccms8#37]
老版本根目录被挂了马，数据库没有。新下载2019.1017程序安装，看了下视频内容页的介绍数据空白，后台文本有。一个个问题排除发现带有html标签的就这样，纯文本就会显示出来。怎么办？

**Comment by Svipa** [comment]
而且调用的是[vod:content]

**Comment by magicblack** [comment]
可以后台关闭数据字段安全过滤。
