### ISSUE TITLE
站群共用一个Memcached有问题

### ISSUE THREAD

**Issue by dage66788** [magicblack/maccms8#41]
共用后数据出现错乱，如何像苹果10那样设置缓存标识

**Comment by zhengnan06577** [comment]
V8的缓存时间有用吗，我的一开启任何一种缓存，都会无视时间，直到硬盘塞满

**Comment by dage66788** [comment]
> V8的缓存时间有用吗，我的一开启任何一种缓存，都会无视时间，直到硬盘塞满

Memcached好像只对常用资源缓存有用

**Comment by magicblack** [comment]
缓存标识在配置文件里搜索cacheid  修改一下即可。
缓存文件是需要 定期 自行清理的。  建议每天清理一次。
