### ISSUE TITLE
Memcached::setSaslAuthData(): SASL is only supported with binary protocol

### ISSUE THREAD

**Issue by aTenb** [magicblack/maccms8#43]
想开启Memcached,验证报错这个。
搜索了一下，要开启二进制，实在找不到哪里开启这个二进制。
Memcached本身是不需要密码和帐号验证就可以读取和写缓存的，多了setSaslAuthData导致完全不知道怎么使用。
宝塔面板默认是不设置帐号和密码链接Memcached，我还算有基础的，通过配置文件找到了帐号密码，但是链接测试，依然报Memcached::setSaslAuthData(): SASL is only supported with binary protocol这个错误。而且不知道怎么处理。
感觉门槛太高了，setSaslAuthData这部验证是否可以取消？或者怎么才能顺利使用

**Comment by magicblack** [comment]
修改php配置文件  memcached.use_sasl = 1
查看phpinfo结果
![image](https://user-images.githubusercontent.com/20452515/79100858-f8735e00-7d99-11ea-84f4-544b556f5cc5.png)
