### ISSUE TITLE
资源站mysqld占用高居不下

### ISSUE THREAD

**Issue by xigua03** [magicblack/maccms8#44]
使用top查看为mysqld占用 数据库配置已优化过 应该怎么解决呢

**Comment by zhengnan06577** [comment]
我也是，怎么解决

**Comment by magicblack** [comment]
可以再后台 站点配置-》 常用-》 安全过滤字段内容 -》 关闭；      即可提高性能。

**Comment by xigua03** [comment]
> 可以再后台站点配置-》 常用-》 安全过滤字段内容-》 关闭； 即可提高性能。

哥 不行 mysql还是在不停的锁表 是不是索引有问题

**Comment by xigua03** [comment]
> > 可以再后台站点配置-》 常用-》 安全过滤字段内容-》 关闭； 即可提高性能。
> 
> 哥 不行 mysql还是在不停的锁表 是不是索引有问题

{maccms:vod pagesize=50 type=all order=desc by=time} 
目前发现是由于这个搜索代码导致的 请问下应该如何解决

**Comment by zhengnan06577** [comment]
502 Bad Gateway，刷新又好了，一会又502了
mysql爆满，求解决

**Comment by magicblack** [comment]
升级到最新版本即可 api里也可以关闭过滤里
