### ISSUE TITLE
搜索页

### ISSUE THREAD

**Issue by M-pub** [magicblack/maccms8#45]
找个v8的站：
访问 www.例子.com/index.php?m=vod-search
会显示该站所有视频的搜索数量和结果页数
然后f5可以无限刷新，没有任何提示拦截。
--------------------------------------
如果是从网页点搜索框进入，再f5刷新是会弹提示框的，
--------
希望大大修复！
--------
v10没有发现该问题！

**Comment by M-pub** [comment]
就是复制/index.php?m=vod-search 到地址栏，进入该页面

**Comment by magicblack** [comment]
后台限制下刷新时间就可以了。这里是可以显示所有数据
