### ISSUE TITLE
搜索页

### ISSUE THREAD

**Issue by M-pub** [magicblack/maccms8#46]
大大，后台限制刷新时间没有用的，我都试过了，通过地址栏/index.php?m=vod-search进入搜索页后，没有任何时间限制，可以一直刷新= =

**Comment by M-pub** [comment]
限制刷新时间设置后，仅对通过搜索框搜索进入后能生效，直接通过链接进入后，会失效

**Comment by magicblack** [comment]
一样的处理，只在页码是第一页的时候判断 时间间隔。
