### ISSUE TITLE
v8 的定时任务生成bug

### ISSUE THREAD

**Issue by M-pub** [magicblack/maccms8#47]
make-info-tab-vod-ac2-nomake
添加make 未生成后，宝塔设置定时访问该任务url，生成的html是按照vod_down.html模板生成的，不是vod_detail.html，貌似v8的定时生成，全是按down模板了。

**Comment by M-pub** [comment]
测试两个站，生成的都是down模板内容

**Comment by magicblack** [comment]
后台生成是否正常。分类里配置的模板页面是否正确？

**Comment by M-pub** [comment]
手动生成正常，分类里的模板页面设置也正常，另外，我测试把down模板内容换成detail内容，然后定时生成成功了，但是生成的视频，id是乱的，串了剧。。比如后台采集的是庆余年，定时生成后变成另外的剧
