### ISSUE TITLE
老哥，后台 缓存 设置 好像出问题了。

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms8#48]
![image](https://user-images.githubusercontent.com/17606183/81655145-9d03c100-9468-11ea-96ab-f67793cca732.png)

**Comment by aoerboquartz** [comment]
如果选择“文件缓存”
然后点 更新参数，会提示 “未发送任何数据”
![image](https://user-images.githubusercontent.com/17606183/81655880-26b38e80-9469-11ea-9e9f-1882d9363e78.png)

**Comment by magicblack** [comment]
关闭服务器防火墙试试看，
