### ISSUE TITLE
最新升级包升级上去后搜索和缓存器无法使用

### ISSUE THREAD

**Issue by ykmov** [magicblack/maccms8#49]
最新升级包升级上去后搜索和缓存器无法使用

**Comment by magicblack** [comment]
具体提示什么，截图上传。

**Comment by ykmov** [comment]
![003](https://user-images.githubusercontent.com/67530312/86090593-f4272900-badc-11ea-9df9-1e2bde2d1ea4.png)
![001](https://user-images.githubusercontent.com/67530312/86090599-f5f0ec80-badc-11ea-839c-523a73fbbf47.png)
![002](https://user-images.githubusercontent.com/67530312/86090597-f5585600-badc-11ea-9737-c58fa7eae0e8.png)
如图，同一台服务器同一个环境，不覆盖升级包的缓存器正常使用，覆盖后选择Memcache和Memcached均无法使用，前台搜索提示：Fatal error: Call to undefined function chkSql() in /www/wwwroot/test/inc/module/vod.php on line 96
同时二次更新规则，勾选图片，图片也更新得不彻底

**Comment by ykmov** [comment]
Fatal error: Call to undefined function chkSql() in /www/wwwroot/test/inc/module/vod.php on line 96

**Comment by magicblack** [comment]
覆盖不全造成的吧。升级包一定要全部覆盖。

**Comment by ykmov** [comment]
![image](https://user-images.githubusercontent.com/67530312/86449465-cfd08400-bd4a-11ea-94b3-328be794c0ce.png)
重新安装一套，问题依旧

**Comment by aoerboquartz** [comment]
@ykmov 问题一样。
你是宝塔搭建的环境么？
我搜索倒是没有问题。
但是 Memcached 缓存的问题和你一样。
开启 常用资源缓存 和 动态页面缓存 之后。
通过 服务端 Memcached 查看负载状态，发现可以缓存，GET请求数数 有数据，但是 无法命中。
