### ISSUE TITLE
mac8 后台Memcache和Memcached 测试问题

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms8#50]
升级到2020.1022最新版之后
1、后台选择Memcache，点测试，提示 “恭喜测试可用”
2、（php扩展 已经卸载了Memcache并安装了Memcached）；后台选择Memcached，点测试，提示 “不可用请检查配置项”
测试php5.6和7.2都是上面的问题。
3、如果选择Memcache，并开启 “常用资源缓存”和“动态页面缓存” ；Memcached服务端确实会缓存，但是 get_hits 命中次数是0。

**Comment by aoerboquartz** [comment]
补充：命中次数不是0了，但是cmd_get 的GET请求数 有5W多，get_hits 的GET命中次数 才只有 几十。是因为我是动态网站没有生成静态的原因么？

**Comment by magicblack** [comment]
不同域名会缓存不同域名下的缓存。
Memcached这个不支持windows吧，再仔细看看。
具体问题具体对待。

**Comment by ykmov** [comment]
linux下，用的宝塔，和他一样的情况

**Comment by magicblack** [comment]
修复了缓存命中问题，稍后更细
