### ISSUE TITLE
苹果cmsV8使用火车头入库，苹果cmsV8程序内部采集参数配置无控制，

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms8#52]
苹果cmsV8使用火车头入库，苹果cmsV8程序内部采集参数配置无控制，不管是火车头新采集的数据还是更新的数据，火车头都是返回发布成功状态，导致再次采集更新时火车头下载的图片会重复上传，是否是因为采集参数配置不受控制导致？

**Comment by magicblack** [comment]
二次更新选项配置， 看看是否更新图片。  本地图片shi 不会再次更新嘚 ~

**Comment by xqd360** [comment]
我表达的意思不是说是否图片会不会更新，而是每次火车头采集发布的是否不论程序中是否有数据，都会提示发布成功，苹果10只有第一次入库的是否会返回发布成功，第二次更新只会返回发布未知

magicblack <notifications@github.com> 于2020年7月8日周三 上午10:04写道：
