### ISSUE TITLE
升级到 1022C 出现了一个新问题。

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms8#53]
文章，添加文章
选择分类，填写标题和内容之后，点保存按钮。
提示：

![image](https://user-images.githubusercontent.com/17606183/87005145-23cae500-c1f1-11ea-8586-0d84e4f4c3cb.png)

**Comment by magicblack** [comment]
你这个问题好像是 文章的名称    汉子转拼音提示的~
输入的什么 名字

**Comment by aoerboquartz** [comment]
输入的是数字。

**Comment by aoerboquartz** [comment]
php从7.2切换到5.6 问题解决。看来对php7.2 支持不好。

**Comment by magicblack** [comment]
好的问题已经修复稍后更新
