### ISSUE TITLE
苹果8内容介绍那里插入图片前段不显示问题。

### ISSUE THREAD

**Issue by woainiquanjia** [magicblack/maccms8#54]
视频添加内容介绍编辑器里面插入了图片，文字可以显示，就是不显示插入的图片，重新安装也是只显示文字，插入的图片没有前段没有显示，请求修复（前段只能看到文字，后端显示是插入了图片但是前段就是不显示）调用绝对没有问题

**Comment by woainiquanjia** [comment]
视频介绍那里插入里图片后台编辑器可以正常显示，但是前端就是不展示插入的图片，但是前端文字可以展示，资讯文章切没有什么问题，就视频内容介绍页的编辑器插入了图片后前端就是不显示。请求修复

**Comment by woainiquanjia** [comment]
苹果8和苹果10都一样编辑器里面都插入了图片，后台编辑器可以显示图片，但是前端就是不显示图片

**Comment by magicblack** [comment]
检查下模板中的标签
	[art:content]   内容
	[art:contenttext] 过滤html代码后内容

**Comment by woainiquanjia** [comment]
不是，vod的编辑器不是art的编辑器------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;magicblack&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月17日(星期五) 晚上8:27
收件人:&nbsp;&quot;magicblack/maccms8&quot;<maccms8@noreply.github.com&gt;;
抄送:&nbsp;&quot;woainiquanjia&quot;<424565494@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms8] 苹果8内容介绍那里插入图片前段不显示问题。 (#54)

**Comment by woainiquanjia** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;magicblack&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月17日(星期五) 晚上8:27
收件人:&nbsp;&quot;magicblack/maccms8&quot;<maccms8@noreply.github.com&gt;;
抄送:&nbsp;&quot;woainiquanjia&quot;<424565494@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms8] 苹果8内容介绍那里插入图片前段不显示问题。 (#54)

**Comment by woainiquanjia** [comment]
我说的事情内容，不是文章文章art没有问题，问题在vod的视频编辑器，你可以添加一部影片看看编辑器插入图片会不会在前端显示------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;magicblack&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月17日(星期五) 晚上8:27
收件人:&nbsp;&quot;magicblack/maccms8&quot;<maccms8@noreply.github.com&gt;;
抄送:&nbsp;&quot;woainiquanjia&quot;<424565494@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms8] 苹果8内容介绍那里插入图片前段不显示问题。 (#54)
