### ISSUE TITLE
为什么我采集的视频名字不全

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms8#56]
为什么我采集的视频名字不全，比如我采集的   二十不惑 DVD 后台视频哪里只有  二十不惑 D

**Comment by magicblack** [comment]
后天管理的时候显示不全？ 那可能是  采集配置里的 名称同义词替换吧。 
如果只是前台模板显示不全 那么是模板标签 或 css样式 的问题。

**Comment by Fewdays** [comment]
原来后台管理也不全 现在我已经修改好了
