### ISSUE TITLE
有一个问题我把自动生成tag关闭了，为什么视频哪里tag还是勾选的自动生成，也没有生成tag

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms8#58]
还有一个问题我把自动生成tag关闭了，为什么视频哪里tag还是勾选的自动生成，也没有生成tag，我也采集不到资源站里面的tag

**Comment by magicblack** [comment]
视频管理中的 tag生成 只有为tag空的时候才会 触发生成条件。
