### ISSUE TITLE
[Msg]: Memcached::set() expects at most 3 parameters, 4 given

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms8#60]
环境：
CentOS 7.3.1611

PHP7.2
PHP 扩展 memcached

服务端Memcached 1.6.7

MACCMS版本 2020.1026
系统设置的缓存类型方式 Memcached
点测试按钮，提示 恭喜测试可用

但是 访问网址，提示 
![image](https://user-images.githubusercontent.com/17606183/99394039-34b30200-2919-11eb-803a-4fdfe1424384.png)

**Comment by aoerboquartz** [comment]
在开启动态页面缓存 的时候，会报这个错误。
开启常用资源缓存 的时候没问题。

**Comment by magicblack** [comment]
稍后修复更新
