### ISSUE TITLE
maccms8评论在视频内容页可以正常翻页，但在文章内容页翻页后出现空白？

### ISSUE THREAD

**Issue by changxiaoliang** [magicblack/maccms8#66]
maccms8评论在视频内容页可以正常翻页，但在文章内容页翻页后出现空白。
当在文章内容页评论翻页后，不会显示评论内容，会提示：暂无评论，快来抢沙发吧！
请修复！谢谢！
以下是在文章内容页评论第一页的截图，第一页是正常的：
![1](https://user-images.githubusercontent.com/32618299/115660320-6b7cc080-a36e-11eb-9c14-e29db96c190a.jpg)
以下是在文章内容页评论第二页的截图，第二页不会显示评论内容，会提示：暂无评论，快来抢沙发吧！：
![2](https://user-images.githubusercontent.com/32618299/115660392-851e0800-a36e-11eb-8bf3-024d41f0bff7.jpg)
在文章内容页评论的论第一页，通过浏览器调试工具，可以看到，评论第二页及以后的url地址里没有写入vid参数：
![3](https://user-images.githubusercontent.com/32618299/115660918-42106480-a36f-11eb-87c7-6146ac98f1f1.jpg)

**Comment by magicblack** [comment]
已经修复
