### ISSUE TITLE
maccms8 cup 为什么老是跑满 请问怎么优化呢

### ISSUE THREAD

**Issue by baobao789** [magicblack/maccms8#69]
![45566](https://user-images.githubusercontent.com/86533324/123523134-6cc2c480-d6f4-11eb-8b9e-b871ccd30cd2.PNG)
我已经数据库性能优化了  也安装缓存器了  但是还是每天都这样 就放一个网站而已

**Comment by magicblack** [comment]
1，站点配置-》性能-》关闭安全字段过滤。
2，开启缓存。
3，静态首页。
4，减少搜索带来的压力，优化mysql和服务器。
