### ISSUE TITLE
优化升级数据库脚本过程

### ISSUE THREAD

**Issue by gangtiexai** [magicblack/maccms8#9]
这个“升级数据库”具体是升级了什么，是优化了表还是性能方面？

database.php这里面优化了什么方面，好像只创建了表，不太懂，请教一下

另外，请教一下，v8可以对接redis数据库吗

**Comment by magicblack** [comment]
是的，这次只是创建里数据库脚本，原来处理数据库升级的时候有问题，现在改进了。后续还有升级~
